# Generated by Django 5.1 on 2024-10-14 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Back Log', 'Back Log'), ('On Hold', 'On Hold'), ('In Progress', 'In Progress'), ('Testing (Client)', 'Testing (Client)'), ('Deployed', 'Deployed')], default='Pending', max_length=20)),
                ('client_work', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
