# Generated by Django 5.1 on 2024-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
